### ISSUE TITLE
Compatibility TYPO3 CMS 8

### ISSUE THREAD

**Issue by fabarea** [xperseguers/t3ext-routing#21]
Hi Xavier,

Quick question: is it anything in the pipeline regarding TYPO3 CMS 8 compatibility? Is it a lot to undertake to achieve that?

Greetings,

Fabien

**Comment by tantegerda1** [comment]
Hi Fabien,

in the git repository this extension is marked as compatible with TYPO3 CMS 8 since ~10 months, please see [first commit](https://github.com/xperseguers/t3ext-routing/commit/244906c4d1a0641202d8a285e6e6c0e8e8b7597e) and [the relevant `ext_emconf.php` line](
https://github.com/xperseguers/t3ext-routing/blob/1737469e15806c968890780e08cff7f0bfd657b0/ext_emconf.php#L38).

I do use this extension successfully in TYPO3 CMS 8 projects - albeit pulled from source via composer (i.e. not the TER version). If you manage your TYPO3 CMS project with composer, this would be like:
```
{
	"repositories": [
		{ "type": "composer", "url": "https://composer.typo3.org/" },
		{ "type": "vcs", "url": "https://github.com/xperseguers/t3ext-routing.git" }
	],
	"require": {
		"typo3/cms": "^8.7",
		"causal/routing": "dev-master"
	},
	"extra": {
		"typo3/cms": {
			"cms-package-dir": "{$vendor-dir}/typo3/cms",
			"web-dir": "web"
		}
	}
}
```
(be sure to use `causal/routing` as composer package name when using directly, whereas when using via the TER composer repository it is `typo3ter/routing`)

I guess it just needs an official TER release. (hint, hint @xperseguers)

Cheers, 
Ludwig

**Comment by fabarea** [comment]
Hi @tantegerda1 

Thank you very much for your reply. I had a *too quick* look into `ext_emconf` and overlooked that info (confused with the PHP 7 compatibility line!) . Indeed, installing the master branch via composer worked fine. Cheers!
