### ISSUE TITLE
Issue with causal/routing dev-master

### ISSUE THREAD

**Issue by ghost** [xperseguers/t3ext-routing#27]
Hi,

when we integrate the causal/routing dev-master on Typo3 8.7.27 through composer,
The website is giving us a 500 error.
When we checked the log file we have the below error

PHP Fatal error:  Uncaught BadFunctionCallException: TYPO3 Fatal Error: Extension key "core" is NOT loaded!

Are we missing any module that is required for it?

**Comment by tantegerda1** [comment]
Are you sure this is caused by `EXT:routing` and not by another extension you installed?
The logged error message is caused by an extension that specifies the TYPO3 system extension  `core` as one of it's dependencies ("constraints" / "depends") in `ext_emconf.php`. The naming of system extensions and how you'd specify them as dependencies changed quite a bit between TYPO3 8 and TYPO3 9. As far as I know, `EXT:routing` is not yet made compatible to TYPO3 9.

Now, which version of an extension you _actually_ get depends the on the configured [`repositories`](https://getcomposer.org/doc/04-schema.md#repositories) in your `composer.json`, the php version used to execute the command `composer update` or `composer require` and whatever else is required in your `composer.json`. So, `dev-master` is a bit vague here. Could you post the content of your `typo3conf/ext/routing/ext_emconf.php` here?

Besides that, could you look through all of your `typo3conf/ext/*/ext_emconf.php` files for one or more that depend on `core`?

**Comment by xperseguers** [comment]
Cannot reproduce.
